export const categories = [
  { value: "electronics", label: "Electronics" },
  { value: "fashion", label: "Fashion" },
  { value: "grocery", label: "Grocery" },
  { value: "home_appliances", label: "Home Appliances" },
  { value: "books", label: "Books" },
  { value: "toys", label: "Toys & Games" },
  { value: "furniture", label: "Furniture" },
  { value: "sports", label: "Sports & Fitness" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "automotive", label: "Automotive" },
  { value: "jewelry", label: "Jewelry & Accessories" },
  { value: "health", label: "Health & Wellness" },
  { value: "stationery", label: "Stationery & Office Supplies" },
  { value: "pet_supplies", label: "Pet Supplies" },
  { value: "music", label: "Music & Instruments" },
  { value: "garden", label: "Garden & Outdoor" },
  { value: "footwear", label: "Footwear" },
  { value: "bags", label: "Bags & Luggage" },
  { value: "baby", label: "Baby & Kids" },
  { value: "software", label: "Software & Digital Products" },
];
