import Header from '../shared/widgets/header';
import './global.css';
import {Poppins,Roboto} from 'next/font/google';
export const metadata = {
  title: 'Eshop User UI',
  description: 'Generated by create-nx-workspace',
};
import 'remixicon/fonts/remixicon.css'

const poppins = Poppins({ subsets: ['latin'],
  weight:['100','300','400','500','700','900'],
  style:['normal','italic'],
  variable:'--font-poppins'
 });
const roboto = Roboto({ subsets: ['latin'], 
  weight:['100','300','400','500','700','900'],
  style:['normal','italic'],
  variable:'--font-roboto'
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${roboto.variable}`}>
        <Header/>
        {children}</body>
    </html>
  );
}
