import './global.css';
import Providers from './providers';
import {Poppins,Roboto} from 'next/font/google';
import 'remixicon/fonts/remixicon.css'
export const metadata = {
  title: 'Welcome to EShop seller-ui',
  description: 'Generated by create-nx-workspace',
};


const poppins = Poppins({ subsets: ['latin'],
  weight:['100','300','400','500','700','900'],
  style:['normal','italic'],
  variable:'--font-poppins'
 });


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`min-h-screen bg-slate-900 font-sans antialiased ${poppins.variable}`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
